{
 "title": "Demo Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Demo Dashboard\nThis dashboard show metrics from the first prometheus example"
   },
   "targets": [
    {
     "expr": "rate(globoticket_event_processing_duration_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Node JS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Garbage Collection Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nodejs_gc_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_eventloop_lag_seconds", "legendFormat": "p95" }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 14, "w": 11, "x": 0, "y": 13 } },
  {
   "title": "Total Events Processed",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 11, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "globoticket_events_processed_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Processing Rate",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(globoticket_events_processed_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Health",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Events Processed",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Events" } },
   "targets": [
    {
     "expr": "globoticket_events_processed_total",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(globoticket_events_processed_total[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Event Processing Latency Distribution",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(globoticket_event_processing_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(globoticket_event_processing_duration_seconds_bucket[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(globoticket_event_processing_duration_seconds_bucket[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(globoticket_event_processing_duration_seconds_bucket[5m])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(globoticket_event_processing_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(globoticket_event_processing_duration_seconds_bucket[5m])))",
     "legendFormat": "p25"
    }
   ]
  },
  {
   "title": "Event Processing Throughput Distribution",
   "type": "timeseries",
   "description": "How many requests per second for each bucket",
   "gridPos": { "h": 14, "w": 13, "x": 11, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(globoticket_event_processing_duration_seconds_bucket[$__rate_interval])",
     "legendFormat": "Bucket: <= {{le}} s"
    }
   ]
  }
 ]
}